/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Echo2Service_H
#define Echo2Service_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "echo_types.h"

namespace example {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class Echo2ServiceIf {
 public:
  virtual ~Echo2ServiceIf() {}
  virtual void Echo2(Echo2Response& _return, const Echo2Request& request) = 0;
};

class Echo2ServiceIfFactory {
 public:
  typedef Echo2ServiceIf Handler;

  virtual ~Echo2ServiceIfFactory() {}

  virtual Echo2ServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(Echo2ServiceIf* /* handler */) = 0;
};

class Echo2ServiceIfSingletonFactory : virtual public Echo2ServiceIfFactory {
 public:
  Echo2ServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<Echo2ServiceIf>& iface) : iface_(iface) {}
  virtual ~Echo2ServiceIfSingletonFactory() {}

  virtual Echo2ServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(Echo2ServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<Echo2ServiceIf> iface_;
};

class Echo2ServiceNull : virtual public Echo2ServiceIf {
 public:
  virtual ~Echo2ServiceNull() {}
  void Echo2(Echo2Response& /* _return */, const Echo2Request& /* request */) {
    return;
  }
};

typedef struct _Echo2Service_Echo2_args__isset {
  _Echo2Service_Echo2_args__isset() : request(false) {}
  bool request :1;
} _Echo2Service_Echo2_args__isset;

class Echo2Service_Echo2_args {
 public:

  Echo2Service_Echo2_args(const Echo2Service_Echo2_args&);
  Echo2Service_Echo2_args& operator=(const Echo2Service_Echo2_args&);
  Echo2Service_Echo2_args() {
  }

  virtual ~Echo2Service_Echo2_args() throw();
  Echo2Request request;

  _Echo2Service_Echo2_args__isset __isset;

  void __set_request(const Echo2Request& val);

  bool operator == (const Echo2Service_Echo2_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const Echo2Service_Echo2_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Echo2Service_Echo2_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Echo2Service_Echo2_pargs {
 public:


  virtual ~Echo2Service_Echo2_pargs() throw();
  const Echo2Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Echo2Service_Echo2_result__isset {
  _Echo2Service_Echo2_result__isset() : success(false) {}
  bool success :1;
} _Echo2Service_Echo2_result__isset;

class Echo2Service_Echo2_result {
 public:

  Echo2Service_Echo2_result(const Echo2Service_Echo2_result&);
  Echo2Service_Echo2_result& operator=(const Echo2Service_Echo2_result&);
  Echo2Service_Echo2_result() {
  }

  virtual ~Echo2Service_Echo2_result() throw();
  Echo2Response success;

  _Echo2Service_Echo2_result__isset __isset;

  void __set_success(const Echo2Response& val);

  bool operator == (const Echo2Service_Echo2_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Echo2Service_Echo2_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Echo2Service_Echo2_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Echo2Service_Echo2_presult__isset {
  _Echo2Service_Echo2_presult__isset() : success(false) {}
  bool success :1;
} _Echo2Service_Echo2_presult__isset;

class Echo2Service_Echo2_presult {
 public:


  virtual ~Echo2Service_Echo2_presult() throw();
  Echo2Response* success;

  _Echo2Service_Echo2_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class Echo2ServiceClient : virtual public Echo2ServiceIf {
 public:
  Echo2ServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  Echo2ServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void Echo2(Echo2Response& _return, const Echo2Request& request);
  void send_Echo2(const Echo2Request& request);
  void recv_Echo2(Echo2Response& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class Echo2ServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<Echo2ServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (Echo2ServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_Echo2(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  Echo2ServiceProcessor(::apache::thrift::stdcxx::shared_ptr<Echo2ServiceIf> iface) :
    iface_(iface) {
    processMap_["Echo2"] = &Echo2ServiceProcessor::process_Echo2;
  }

  virtual ~Echo2ServiceProcessor() {}
};

class Echo2ServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  Echo2ServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< Echo2ServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< Echo2ServiceIfFactory > handlerFactory_;
};

class Echo2ServiceMultiface : virtual public Echo2ServiceIf {
 public:
  Echo2ServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<Echo2ServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~Echo2ServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<Echo2ServiceIf> > ifaces_;
  Echo2ServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<Echo2ServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void Echo2(Echo2Response& _return, const Echo2Request& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Echo2(_return, request);
    }
    ifaces_[i]->Echo2(_return, request);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class Echo2ServiceConcurrentClient : virtual public Echo2ServiceIf {
 public:
  Echo2ServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  Echo2ServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void Echo2(Echo2Response& _return, const Echo2Request& request);
  int32_t send_Echo2(const Echo2Request& request);
  void recv_Echo2(Echo2Response& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
